// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WingApi.Classes.Database;

namespace WingApi.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20210402075522_farerule")]
    partial class farerule
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WingApi.Classes.Database.tblAirlineFareRule", b =>
                {
                    b.Property<int>("AirlineFareRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CabinBaggage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CancellationAdditionalCharge")
                        .HasColumnType("float");

                    b.Property<double>("CancellationCharge")
                        .HasColumnType("float");

                    b.Property<string>("CancellationPolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckingBaggage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ReissueAdditionalCharge")
                        .HasColumnType("float");

                    b.Property<double>("ReissueCharge")
                        .HasColumnType("float");

                    b.Property<string>("ReissuePolicy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceProvider")
                        .HasColumnType("int");

                    b.Property<string>("resultIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("traceId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirlineFareRuleId");

                    b.ToTable("tblAirlineFareRule");
                });

            modelBuilder.Entity("WingApi.Classes.Database.tblTboFareRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GenrationDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraceId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblTboFareRule");
                });

            modelBuilder.Entity("WingApi.Classes.Database.tblTboTokenDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AgencyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GenrationDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MemberId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblTboTokenDetails");
                });

            modelBuilder.Entity("WingApi.Classes.Database.tblTboTravelDetail", b =>
                {
                    b.Property<int>("TravelDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdultCount")
                        .HasColumnType("int");

                    b.Property<int>("CabinClass")
                        .HasColumnType("int");

                    b.Property<int>("ChildCount")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GenrationDt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InfantCount")
                        .HasColumnType("int");

                    b.Property<int>("JourneyType")
                        .HasColumnType("int");

                    b.Property<double>("MinPublishFare")
                        .HasColumnType("float");

                    b.Property<double>("MinPublishFareReturn")
                        .HasColumnType("float");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TravelDetailId");

                    b.ToTable("tblTboTravelDetail");
                });

            modelBuilder.Entity("WingApi.Classes.Database.tblTboTravelDetailResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JsonData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OfferedFare")
                        .HasColumnType("float");

                    b.Property<double>("PublishedFare")
                        .HasColumnType("float");

                    b.Property<string>("ResultIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TravelDetailId")
                        .HasColumnType("int");

                    b.Property<int>("segmentId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("TravelDetailId");

                    b.ToTable("tblTboTravelDetailResult");
                });

            modelBuilder.Entity("WingApi.Classes.Database.tblTripJackFareRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("GenrationDt")
                        .HasColumnType("datetime2");

                    b.Property<string>("JsonData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraceId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblTripJackFareRule");
                });

            modelBuilder.Entity("WingApi.Classes.Database.tblTripJackTravelDetail", b =>
                {
                    b.Property<int>("TravelDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdultCount")
                        .HasColumnType("int");

                    b.Property<int>("CabinClass")
                        .HasColumnType("int");

                    b.Property<int>("ChildCount")
                        .HasColumnType("int");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpireDt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GenrationDt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InfantCount")
                        .HasColumnType("int");

                    b.Property<int>("JourneyType")
                        .HasColumnType("int");

                    b.Property<double>("MinPublishFare")
                        .HasColumnType("float");

                    b.Property<double>("MinPublishFareReturn")
                        .HasColumnType("float");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TravelDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TravelDetailId");

                    b.ToTable("tblTripJackTravelDetail");
                });

            modelBuilder.Entity("WingApi.Classes.Database.tblTripJackTravelDetailResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JsonData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OfferedFare")
                        .HasColumnType("float");

                    b.Property<double>("PublishedFare")
                        .HasColumnType("float");

                    b.Property<string>("ResultIndex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TravelDetailId")
                        .HasColumnType("int");

                    b.Property<int>("segmentId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("TravelDetailId");

                    b.ToTable("tblTripJackTravelDetailResult");
                });

            modelBuilder.Entity("WingApi.Classes.Database.tblTboTravelDetailResult", b =>
                {
                    b.HasOne("WingApi.Classes.Database.tblTboTravelDetail", "tblTboTravelDetail")
                        .WithMany("tblTboTravelDetailResult")
                        .HasForeignKey("TravelDetailId");

                    b.Navigation("tblTboTravelDetail");
                });

            modelBuilder.Entity("WingApi.Classes.Database.tblTripJackTravelDetailResult", b =>
                {
                    b.HasOne("WingApi.Classes.Database.tblTripJackTravelDetail", "tblTripJackTravelDetail")
                        .WithMany("tblTripJackTravelDetailResult")
                        .HasForeignKey("TravelDetailId");

                    b.Navigation("tblTripJackTravelDetail");
                });

            modelBuilder.Entity("WingApi.Classes.Database.tblTboTravelDetail", b =>
                {
                    b.Navigation("tblTboTravelDetailResult");
                });

            modelBuilder.Entity("WingApi.Classes.Database.tblTripJackTravelDetail", b =>
                {
                    b.Navigation("tblTripJackTravelDetailResult");
                });
#pragma warning restore 612, 618
        }
    }
}
